# Generated by Django 4.2 on 2024-01-31 13:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ingredients', models.TextField()),
                ('calories', models.DecimalField(decimal_places=2, max_digits=6)),
                ('protein', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Белки')),
                ('fats', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Жиры')),
                ('carbohydrates', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Углеводы')),
                ('fiber', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Клетчатка')),
                ('sugar', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Сахара')),
                ('sodium', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Натрий')),
            ],
        ),
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_steps_count', models.BooleanField(default=True, verbose_name='Показывать количество шагов')),
                ('show_gym_sessions', models.BooleanField(default=True, verbose_name='Показывать занятия в спортзале')),
                ('show_diet_type', models.BooleanField(default=True, verbose_name='Показывать тип диеты')),
                ('show_notes', models.BooleanField(default=True, verbose_name='Показывать заметки')),
                ('show_nutrition_goals', models.BooleanField(default=True, verbose_name='Показывать цели питания')),
                ('show_status', models.BooleanField(default=True, verbose_name='Показывать статус плана')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MealPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_calories', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Общая калорийность')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
                ('steps_count', models.IntegerField(verbose_name='Количество шагов в сутки')),
                ('gym_sessions_count', models.IntegerField(default=3, verbose_name='Количество занятий в спортзале в неделю')),
                ('gym_sessions_duration', models.IntegerField(default=60, verbose_name='Сколько длится одно занятие в спортзале')),
                ('diet_type', models.CharField(blank=True, max_length=50, verbose_name='Тип диеты')),
                ('nutrition_goals', models.CharField(blank=True, max_length=100, verbose_name='Цели питания')),
                ('status', models.CharField(blank=True, choices=[('planned', 'Запланировано'), ('completed', 'Выполнено'), ('skipped', 'Пропущено')], max_length=50, verbose_name='Статус плана')),
                ('dishes', models.ManyToManyField(to='recommendations_app.dish')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
