# Generated by Django 4.2 on 2024-01-28 18:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('PlanEat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ingredients', models.TextField()),
                ('calories', models.DecimalField(decimal_places=2, max_digits=6)),
                ('protein', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Белки')),
                ('fats', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Жиры')),
                ('carbohydrates', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Углеводы')),
                ('fiber', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Клетчатка')),
                ('sugar', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Сахара')),
                ('sodium', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Натрий')),
            ],
        ),
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_steps_count', models.BooleanField(default=True, verbose_name='Показывать количество шагов')),
                ('show_gym_sessions', models.BooleanField(default=True, verbose_name='Показывать занятия в спортзале')),
                ('show_diet_type', models.BooleanField(default=True, verbose_name='Показывать тип диеты')),
                ('show_breakfast_time', models.BooleanField(default=True, verbose_name='Показывать время завтрака')),
                ('show_lunch_time', models.BooleanField(default=True, verbose_name='Показывать время обеда')),
                ('show_dinner_time', models.BooleanField(default=True, verbose_name='Показывать время ужина')),
                ('show_snack_times', models.BooleanField(default=True, verbose_name='Показывать время перекусов')),
                ('show_notes', models.BooleanField(default=True, verbose_name='Показывать заметки')),
                ('show_nutrition_goals', models.BooleanField(default=True, verbose_name='Показывать цели питания')),
                ('show_status', models.BooleanField(default=True, verbose_name='Показывать статус плана')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MealPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_calories', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Общая калорийность')),
                ('breakfast_time', models.TimeField(blank=True, null=True, verbose_name='Время завтрака')),
                ('lunch_time', models.TimeField(blank=True, null=True, verbose_name='Время обеда')),
                ('dinner_time', models.TimeField(blank=True, null=True, verbose_name='Время ужина')),
                ('snack_times', models.TextField(blank=True, null=True, verbose_name='Время перекусов')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
                ('steps_count', models.IntegerField(verbose_name='Количество шагов')),
                ('gym_sessions_count', models.IntegerField(default=0, verbose_name='Количество занятий в спортзале')),
                ('gym_sessions_duration', models.DurationField(verbose_name='Общее время занятий в спортзале')),
                ('diet_type', models.CharField(blank=True, max_length=50, verbose_name='Тип диеты')),
                ('nutrition_goals', models.CharField(blank=True, max_length=100, verbose_name='Цели питания')),
                ('status', models.CharField(blank=True, max_length=50, verbose_name='Статус плана')),
                ('dishes', models.ManyToManyField(to='PlanEat.dish')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
