# Generated by Django 4.2 on 2024-01-29 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlanEat', '0002_dish_userpreferences_mealplan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mealplan',
            name='breakfast_time',
        ),
        migrations.RemoveField(
            model_name='mealplan',
            name='dinner_time',
        ),
        migrations.RemoveField(
            model_name='mealplan',
            name='lunch_time',
        ),
        migrations.RemoveField(
            model_name='mealplan',
            name='snack_times',
        ),
        migrations.RemoveField(
            model_name='userpreferences',
            name='show_breakfast_time',
        ),
        migrations.RemoveField(
            model_name='userpreferences',
            name='show_dinner_time',
        ),
        migrations.RemoveField(
            model_name='userpreferences',
            name='show_lunch_time',
        ),
        migrations.RemoveField(
            model_name='userpreferences',
            name='show_snack_times',
        ),
        migrations.AlterField(
            model_name='mealplan',
            name='gym_sessions_duration',
            field=models.IntegerField(default=60, verbose_name='Сколько длится одно занятие в спортзале'),
        ),
        migrations.AlterField(
            model_name='mealplan',
            name='status',
            field=models.CharField(blank=True, choices=[('planned', 'Запланировано'), ('completed', 'Выполнено'), ('skipped', 'Пропущено')], max_length=50, verbose_name='Статус плана'),
        ),
    ]
