# Generated by Django 4.2 on 2024-01-31 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PlanEat', '0003_remove_mealplan_breakfast_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mealplan',
            name='dishes',
        ),
        migrations.RemoveField(
            model_name='mealplan',
            name='user',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userpreferences',
            name='user',
        ),
        migrations.DeleteModel(
            name='Dish',
        ),
        migrations.DeleteModel(
            name='MealPlan',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='UserPreferences',
        ),
    ]
